- name: Include vars/om-vars.yaml written by terraform during deploy
  include_vars:
    file: vars/om-vars.yaml

- name: Download .deb
  get_url:
    url: "{{ om_url.0 }}/download/agent/automation/mongodb-mms-automation-agent-manager_latest_amd64.ubuntu1604.deb"
    dest: /home/ubuntu/mongodb-agent.deb
    mode: '0640'

- name: "Install MongoDB Enterprise dependencies via apt"
  become: yes
  become_user: root
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
        - libcurl4
        - libgssapi-krb5-2
        - libkrb5-dbg
        - libpci3
        - libsasl2-2
        - snmp
        - liblzma5
        - openssl

- name: Stop mongodb-mms-automation-agent.service if exists
  become: yes
  become_user: root
  shell: if systemctl is-enabled --quiet mongodb-mms-automation-agent; then systemctl stop mongodb-mms-automation-agent && echo stopped; fi
  register: output
  changed_when: "'stopped' in output.stdout"

- name: Install a .deb package
  become: yes
  become_user: root
  apt:
    deb: /home/ubuntu/mongodb-agent.deb

- name: Replace agent settings
  become: yes
  become_user: root
  lineinfile:
    path: /etc/mongodb-mms/automation-agent.config
    regexp: '^mmsGroupId='
    line: mmsGroupId={{project_id}}

- name: Replace agent settings
  become: yes
  become_user: root
  lineinfile:
    path: /etc/mongodb-mms/automation-agent.config
    regexp: '^mmsApiKey='
    line: mmsApiKey={{api_key}}

- name: Replace agent settings
  become: yes
  become_user: root
  lineinfile:
    path: /etc/mongodb-mms/automation-agent.config
    regexp: '^mmsBaseUrl='
    line: mmsBaseUrl={{ om_url.0 }}

- name: Create data directory
  become: yes
  become_user: root
  file:
    path: /data
    state: directory
    recurse: yes
    owner: mongodb
    group: mongodb

- name: "Enable mongodb-mms-automation-agent service"
  become: yes
  become_user: root
  service:
    name: mongodb-mms-automation-agent
    enabled: yes

- name: "Start mongodb-mms-automation-agent service"
  become: yes
  become_user: root
  service: name=mongodb-mms-automation-agent state=started
