- name: Install extras on CentOS
  import_tasks: rhel.yml
  when: ansible_facts['os_family'] == 'RedHat'

- name: Install extras on Ubuntu
  import_tasks: ubuntu.yml
  when: ansible_facts['os_family'] == 'Debian'

- name: Install extras on Suse
  import_tasks: suse.yml
  when: ansible_facts['os_family'] == 'Suse'
