- name: SUSE, import repo key from MongoDB
  become: true
  become_user: root
  ansible.builtin.rpm_key:
    state: present
    key: https://pgp.mongodb.com/server-6.0.asc

- name: SUSE, add MongoDB repository
  become: true
  become_user: root
  community.general.zypper_repository:
    name: mongodb
    repo: 'https://repo.mongodb.com/zypper/suse/15/mongodb-enterprise/6.0/x86_64/'
    state: present
  when: version == "db_6_0_latest"

- name: SUSE, add MongoDB repository
  become: true
  become_user: root
  community.general.zypper_repository:
    name: mongodb
    repo: 'https://repo.mongodb.com/zypper/suse/15/mongodb-enterprise/7.0/x86_64/'
    state: present
  when: version == "db_7_0_latest"

- name: SUSE, stop mongod if running/exists
  become: true
  become_user: root
  shell: if systemctl is-enabled --quiet mongod; then systemctl stop mongod && echo stopped ; fi
  register: output
  changed_when: "'stopped' in output.stdout"

- name: SUSE, install mongodb-enterprise
  become: true
  become_user: root
  community.general.zypper:
    name: mongodb-enterprise
    state: present
    update_cache: yes

- name: SUSE, mongod.conf bind to 0.0.0.0
  become: true
  become_user: root
  lineinfile:
    path: /etc/mongod.conf
    regexp: '^  bindIp: '
    line: '  bindIp: 0.0.0.0'

- name: mongod.conf enable replication 1
  become: true
  become_user: root
  lineinfile:
    path: /etc/mongod.conf
    regexp: '#replication:'
    line: 'replication:'
  vars:
    HOST_COUNT: "{{ groups['amd64_backing_appdb'] | length }}"
  when: "HOST_COUNT | int >= 3"

- name: mongod.conf enable replication 2
  become: true
  become_user: root
  lineinfile:
    path: /etc/mongod.conf
    line: '  replSetName: "AppDB"'
    insertafter: 'replication:'
  vars:
    HOST_COUNT: "{{ groups['amd64_backing_appdb'] | length }}"
  when: "HOST_COUNT | int >= 3"

- name: SUSE, Enable mongod service
  become: true
  become_user: root
  service:
    name: mongod
    enabled: yes

- name: SUSE, Start mongod service
  become: true
  become_user: root
  service: name=mongod state=started

- name: mongod.conf enable replication 3
  ansible.builtin.command: "mongo --eval 'rs.initiate()'"
  run_once: true
  delegate_to: "{{ groups['amd64_backing_appdb'].0 }}"
  vars:
    HOST_COUNT: "{{ groups['amd64_backing_appdb'] | length }}"
  when: "HOST_COUNT | int >= 3"
  
- name: mongod.conf enable replication 4
  command: mongo --eval 'rs.add("{{ item }}:27017")'
  delegate_to: "{{ groups['amd64_backing_appdb'].0 }}"
  run_once: true
  vars:
    HOST_COUNT: "{{ groups['amd64_backing_appdb'] | length }}"
  when: "HOST_COUNT | int >= 3"
  loop: "{{ amd64_backing_appdb }}"